version:
jobs:
  build:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: upload-coverage
          command: npm run coveralls
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./build/test-results.xml
workflows:
  version: 2
  build:
    jobs:
      - build:
          # All branches, all tags.
          filters:
            tags:
              only: /.*/
